-- 코드를 작성해주세요
select COUNT(*) as COUNT
from ECOLI_DATA
where SUBSTR(BIN(GENOTYPE), CHAR_LENGTH(BIN(GENOTYPE))-1, 1) = 0
    and (SUBSTR(BIN(GENOTYPE), CHAR_LENGTH(BIN(GENOTYPE)), 1) = 1
         or SUBSTR(BIN(GENOTYPE), CHAR_LENGTH(BIN(GENOTYPE))-2, 1) = 1)
