select I.ID as ID, FISH_NAME, LENGTH
from FISH_INFO I join
    FISH_NAME_INFO N on I.FISH_TYPE = N.FISH_TYPE
where (I.FISH_TYPE, LENGTH) in (select FISH_TYPE, MAX(LENGTH) as LENGTH from FISH_INFO group by FISH_TYPE)